"""empty message

Revision ID: 1661ba403bab
Revises: 776c14e0cb6d
Create Date: 2024-02-29 12:33:46.965641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1661ba403bab'
down_revision = '776c14e0cb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('tarjeta_credito', 'transferencia', 'financiacion', name='pago_enum'), nullable=False),
    sa.Column('fecha_pago', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('descuento', sa.Boolean(), nullable=True),
    sa.Column('cupon', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desestimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.String(length=40), nullable=False),
    sa.Column('dentro_plazo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desestimiento')
    op.drop_table('compra')
    # ### end Alembic commands ###
