"""empty message

Revision ID: 1ff5712361ef
Revises: 8c7253d9b01f
Create Date: 2024-03-08 18:43:10.290124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff5712361ef'
down_revision = '8c7253d9b01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('nombre_modulo',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('contenido_modulo',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('contenido_modulo',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
        batch_op.alter_column('nombre_modulo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
