"""empty message

Revision ID: 270325d99822
Revises: 562433b4811f
Create Date: 2024-03-11 19:57:13.880283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270325d99822'
down_revision = '562433b4811f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('contenido_modulo',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('contenido_modulo',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
