"""empty message

Revision ID: 4addccd7df84
Revises: 8d12a09ac39d
Create Date: 2024-03-10 12:11:31.525751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4addccd7df84'
down_revision = '8d12a09ac39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.LargeBinary(), nullable=True))
        batch_op.drop_constraint('user_id_profile_picture_key', type_='unique')
        batch_op.drop_column('id_profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_profile_picture', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_id_profile_picture_key', ['id_profile_picture'])
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
