"""empty message

Revision ID: 4fe75b36dafc
Revises: 1661ba403bab
Create Date: 2024-02-29 12:41:38.714065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe75b36dafc'
down_revision = '1661ba403bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contenido__curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=30), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contenido__curso')
    # ### end Alembic commands ###
