"""empty message

Revision ID: 776c14e0cb6d
Revises: 8f7a65ae4ca2
Create Date: 2024-02-29 12:18:45.143367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776c14e0cb6d'
down_revision = '8f7a65ae4ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso')
    # ### end Alembic commands ###
