"""empty message

Revision ID: 8d12a09ac39d
Revises: c54073740ed3
Create Date: 2024-03-10 11:34:20.526572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d12a09ac39d'
down_revision = 'c54073740ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id_profile_picture',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id_profile_picture',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
