"""empty message

Revision ID: 8f7a65ae4ca2
Revises: 
Create Date: 2024-02-29 12:14:00.414440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7a65ae4ca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('userName', sa.String(length=80), nullable=False),
    sa.Column('firstName', sa.String(length=80), nullable=False),
    sa.Column('lastName', sa.String(length=80), nullable=False),
    sa.Column('birthDay', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.Enum('masculino', 'femenino', 'no_binario', name='gender_enum'), nullable=False),
    sa.Column('id_profile_picture', sa.Integer(), nullable=True),
    sa.Column('profesor', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.String(length=80), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('idioma_español', sa.Boolean(), nullable=False),
    sa.Column('ultima_conexion', sa.String(length=40), nullable=False),
    sa.Column('mentor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_profile_picture'),
    sa.UniqueConstraint('telephone'),
    sa.UniqueConstraint('userName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
