"""empty message

Revision ID: b3b7cf65296c
Revises: 5e66eac8992c
Create Date: 2024-03-08 12:44:36.347561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b7cf65296c'
down_revision = '5e66eac8992c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('contenido_modulo',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('contenido_modulo',
               existing_type=sa.String(length=1100),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
