"""empty message

Revision ID: b5d907adf9f7
Revises: 4fd5777a12b0
Create Date: 2024-03-10 11:19:46.774708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5d907adf9f7'
down_revision = '4fd5777a12b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_id_profile_picture_key', type_='unique')
        batch_op.drop_column('id_profile_picture')
        batch_op.drop_column('telephone')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('mentor')
        batch_op.drop_column('profesor')
        batch_op.drop_column('idioma_español')
        batch_op.drop_column('ultima_conexion')
        batch_op.drop_column('country')
        batch_op.drop_column('gender')
        batch_op.drop_column('address')
        batch_op.drop_column('birthDay')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthDay', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', postgresql.ENUM('masculino', 'femenino', 'no_binario', name='gender_enum'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ultima_conexion', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('idioma_español', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profesor', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mentor', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_profile_picture', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_id_profile_picture_key', ['id_profile_picture'])

    # ### end Alembic commands ###
