"""empty message

Revision ID: b75a99ec6f54
Revises: b3b7cf65296c
Create Date: 2024-03-08 18:03:34.807568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75a99ec6f54'
down_revision = 'b3b7cf65296c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('contenido_modulo',
               existing_type=sa.VARCHAR(length=1100),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.alter_column('contenido_modulo',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1100),
               existing_nullable=False)

    # ### end Alembic commands ###
