"""empty message

Revision ID: c54073740ed3
Revises: cf612c65529e
Create Date: 2024-03-10 11:26:05.579728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54073740ed3'
down_revision = 'cf612c65529e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthDay', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Enum('masculino', 'femenino', 'no_binario', name='gender_enum'), nullable=True))
        batch_op.add_column(sa.Column('id_profile_picture', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profesor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('idioma_español', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ultima_conexion', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('mentor', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_profile_picture'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mentor')
        batch_op.drop_column('ultima_conexion')
        batch_op.drop_column('idioma_español')
        batch_op.drop_column('address')
        batch_op.drop_column('country')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('profesor')
        batch_op.drop_column('id_profile_picture')
        batch_op.drop_column('gender')
        batch_op.drop_column('birthDay')

    # ### end Alembic commands ###
