"""empty message

Revision ID: d47e626ba616
Revises: 055f5683aa40
Create Date: 2024-03-07 13:41:20.237886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47e626ba616'
down_revision = '055f5683aa40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido_modulo', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modulo', schema=None) as batch_op:
        batch_op.drop_column('contenido_modulo')

    # ### end Alembic commands ###
