"""empty message

Revision ID: f5dee5a3d20a
Revises: bb4756e04763
Create Date: 2024-02-29 13:06:29.953286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dee5a3d20a'
down_revision = 'bb4756e04763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mas_informacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('first_Name', sa.String(length=40), nullable=False),
    sa.Column('last_Name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contenido_curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=30), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disponibilidad_mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_calendario', sa.String(length=40), nullable=False),
    sa.Column('id_mentor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mentor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno_modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=False),
    sa.Column('revisado', sa.Boolean(), nullable=False),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_alumno'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mas__informacion')
    op.drop_table('disponibilidad__mentor')
    op.drop_table('alumno__modulo')
    op.drop_table('contenido__curso')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contenido__curso',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_curso', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('duracion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id_profesor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], name='contenido__curso_id_curso_fkey'),
    sa.ForeignKeyConstraint(['id_profesor'], ['user.id'], name='contenido__curso_id_profesor_fkey'),
    sa.PrimaryKeyConstraint('id', name='contenido__curso_pkey')
    )
    op.create_table('alumno__modulo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_modulo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_alumno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entregado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('revisado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('aprobado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_alumno'], ['user.id'], name='alumno__modulo_id_alumno_fkey'),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulo.id'], name='alumno__modulo_id_modulo_fkey'),
    sa.PrimaryKeyConstraint('id', name='alumno__modulo_pkey')
    )
    op.create_table('disponibilidad__mentor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('link_calendario', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('id_mentor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_mentor'], ['user.id'], name='disponibilidad__mentor_id_mentor_fkey'),
    sa.PrimaryKeyConstraint('id', name='disponibilidad__mentor_pkey')
    )
    op.create_table('mas__informacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_curso', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_Name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('last_Name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mas__informacion_pkey')
    )
    op.drop_table('alumno_modulo')
    op.drop_table('disponibilidad_mentor')
    op.drop_table('contenido_curso')
    op.drop_table('mas_informacion')
    # ### end Alembic commands ###
